    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Define la codificación de caracteres -->
    <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
    <!-- Define el autor del documento -->
    <meta name="author" content="Tomás Luís Polo Gutiérrez" />
    <!-- Define el programa con el que se ha generado el documento -->
    <meta name="generator" content="NetBeans 8.2" />
    <!-- Define el copyright del documento -->
    <meta name="copyright" content="DWES" />
    <!-- Define el comportamiento de los buscadores -->
    <meta name="robots" content="index, follow" />
    <!-- Define las palabras claves del contenido del documento -->
    <meta name="keywords" content="GestionSesionesTomasPG" />
    <!-- Define una breve descripción del sitio -->
    <meta name="description" content="Gestion usuarios en session" />
